### ISSUE TITLE
Change representation of probabilities to 0-1

### ISSUE THREAD

**Issue by MonsterUntermBett** [bit-bots/bitbots_navigation#20]
Currently the probabilities of each measurement to be actually sensed by a particle are represented as values between -10 and 100 (0-100 on the map/field and -10 outside).
This works, but lacks any mathematical foundation.
The values need to be changed to be between 0 and 1 for probabilities on the map. 
A good representation for measurements that would be outside the map needs to be found. 

- [ ]  adapt map generator script

- [ ] update models

- [x]  adapt map model (https://github.com/bit-bots/bitbots_navigation/blob/58c98855faf0d1bd8202b542a2ed11126519f237/bitbots_localization/src/map.cpp#L33)

- [ ] instead of adding all single measurement probabilitiess, they need to by multiplied (https://github.com/bit-bots/bitbots_navigation/blob/58c98855faf0d1bd8202b542a2ed11126519f237/bitbots_localization/src/ObservationModel.cpp#L53), see Thrun  p. 143

**Comment by Flova** [comment]
- Due to better viewability and support in the image formats I would keep the raw map in a range from o to 100 (better 0 to 255 to use the full byte). They can be scaled down if the map is accessed (see PR #57 )
- What do you mean with update models?
- If we multiply all measurements, a false positive line point with a rating of 0 could result in a overall measurement prob of zero even if all other points matched correctly. Or is this wrong?

**Comment by MonsterUntermBett** [comment]
> 
> 
>     * Due to better viewability and support in the image formats I would keep the raw map in a range from o to 100 (better 0 to 255 to use the full byte). They can be scaled down if the map is accessed (see PR #57 )
Okay
> 
>     * What do you mean with update models?
The maps and the map_generator need to be adjusted

>     * If we multiply all measurements, a false positive line point with a rating of 0 could result in a overall measurement prob of zero even if all other points matched correctly. Or is this wrong?

yes. perhaps the smallest prob could simply be very close to zero

**Comment by Flova** [comment]
See Issue #58 for further discussion.
